Repository testcontainers/testcontainers-node, pull requests merged in 2020-09, with the labels that each got.

#122 Customise release-drafter
  .github/release-drafter.yml
Labels: maintenance

#123 Update dependencies
  package-lock.json
  package.json
  src/modules/kafka/kafka-container.test.ts
Labels: dependencies

#124 Combine DEBUG=testcontainers with environment variables and move Common Issues
  README.md
Labels: documentation

#126 Separate container logs under new namespace
  README.md
  src/container.ts
  src/docker-client-factory.ts
  src/docker-client.ts
  src/docker-compose-environment.ts
  src/generic-container.ts
  src/logger.ts
  src/network.ts
  src/wait-strategy.ts
Labels: enhancement, minor

#127 Fixes arango test - Have fun!
  src/modules/arangodb/arangodb-container.test.ts
  src/modules/arangodb/arangodb-container.ts
Labels: maintenance

#128 Show Docker pull output
  .nvmrc
  src/docker-client.ts
  src/logger.ts
  src/pull-stream-parser.test.ts
  src/pull-stream-parser.ts
Labels: enhancement

#129 Reword Usage -> Configuration
  README.md
Labels: documentation

#130 Use cross-env for running build on Windows
  package-lock.json
  package.json
  src/generic-container.test.ts
Labels: maintenance

#121 Use moby-ryuk for auto cleanup of resources on unexpected exit
  .github/workflows/node.js.yml
  README.md
  fixtures/docker-compose/docker-compose-port-error.yml
  jest.config.js
  src/container.ts
  src/docker-client-factory.ts
  src/docker-client.ts
  src/docker-compose-container-name-resolver.test.ts
  src/docker-compose-container-name-resolver.ts
  src/docker-compose-environment.test.ts
  src/docker-compose-environment.ts
  src/generic-container.test.ts
  src/generic-container.ts
  src/index.ts
  src/modules/abstract-started-container.ts
  src/modules/arangodb/arangodb-container.test.ts
  src/modules/arangodb/arangodb-container.ts
  src/modules/kafka/README.md
  src/modules/kafka/kafka-container.test.ts
  src/modules/kafka/kafka-container.ts
  src/modules/neo4j/neo4j-container.test.ts
  src/modules/neo4j/neo4j-container.ts
  src/network.ts
  src/reaper.ts
  src/repo-tag.test.ts
  src/repo-tag.ts
  src/test-container.ts
  src/wait-strategy.ts
Labels: enhancement, major

#131 Reaper must be run with privileged mode
  src/reaper.ts
Labels: bug

#132 Reaper host should be Docker host
  src/reaper.ts
Labels: bug

#134 Change type of logs to Readable
  src/container.ts
  src/generic-container.test.ts
  src/generic-container.ts
  src/modules/abstract-started-container.ts
  src/modules/arangodb/arangodb-container.ts
  src/test-container.ts
  src/wait-strategy.ts
Labels: maintenance

#136 Fix Reaper not using DOCKER_HOST if set
  src/docker-client-factory.ts
  src/reaper.ts
  src/test-container.ts
  src/wait-strategy.ts
Labels: bug

#137 Migrate tslint to eslint
  .eslintrc.js
  package-lock.json
  package.json
  src/container.ts
  src/docker-client.ts
  src/generic-container.ts
  src/modules/arangodb/arangodb-container.ts
  src/modules/kafka/kafka-container.test.ts
  src/modules/neo4j/neo4j-container.ts
  src/pull-stream-parser.test.ts
  src/pull-stream-parser.ts
  src/repo-tag.ts
  src/wait-strategy.ts
  tslint.json
Labels: maintenance

#138 Update README to show examples as test cases
  README.md
Labels: documentation

#139 Do not bind the same port twice
  src/port-binder.test.ts
  src/port-binder.ts
Labels: enhancement

#140 Add support for stopping a docker-compose environment
  README.md
  fixtures/docker-compose/docker-compose-with-network.yml
  src/docker-compose-environment.test.ts
  src/docker-compose-environment.ts
  src/index.ts
Labels: enhancement, minor

#142 Fix containers left running after wait strategies fail
  src/generic-container.test.ts
  src/generic-container.ts
  src/wait-strategy.ts
Labels: bug, minor
