Repository testcontainers/testcontainers-node, pull requests merged in 2020-11, with the labels that each got.

#160 Support providing multiple docker-compose files
  README.md
  fixtures/docker-compose/docker-compose-with-override/docker-compose-update.yml
  fixtures/docker-compose/docker-compose-with-override/docker-compose.yml
  src/docker-compose-environment.test.ts
  src/docker-compose-environment.ts
Labels: enhancement, minor

#162 Expose container IP address
  README.md
  src/container.ts
  src/docker-compose-environment.test.ts
  src/docker-compose-environment.ts
  src/generic-container.test.ts
  src/generic-container.ts
  src/modules/abstract-started-container.ts
  src/modules/arangodb/arangodb-container.ts
  src/modules/elasticsearch/elasticsearch-container.ts
  src/modules/kafka/README.md
  src/modules/kafka/kafka-container.test.ts
  src/modules/neo4j/neo4j-container.ts
  src/network.test.ts
  src/test-container.ts
Labels: enhancement, major

#164 Expose host ports to container
  README.md
  package-lock.json
  package.json
  src/container.ts
  src/docker-client-instance.ts
  src/docker-client.ts
  src/docker-compose-environment.ts
  src/generic-container.test.ts
  src/generic-container.ts
  src/index.ts
  src/modules/abstract-started-container.ts
  src/modules/arangodb/arangodb-container.ts
  src/modules/kafka/kafka-container.ts
  src/modules/neo4j/neo4j-container.ts
  src/network.ts
  src/port-check.ts
  src/port-forwarder.ts
  src/reaper.ts
  src/repo-tag.ts
  src/test-container.ts
  src/test-containers.ts
Labels: enhancement, minor

#165 Use ssh-remote-port-forward lib
  package-lock.json
  package.json
  src/port-forwarder.ts
Labels: maintenance, patch

#168 Allow passing custom Kafka and ZK images
  src/generic-container.test.ts
  src/modules/kafka/README.md
  src/modules/kafka/kafka-container.test.ts
  src/modules/kafka/kafka-container.ts
Labels: enhancement, minor

#171 Add possibility to specify custom ryuk image
  README.md
  src/reaper.ts
Labels: enhancement, minor
