Repository testcontainers/testcontainers-node, pull requests merged in 2020-10, with the labels that each got.

#143 Remove docker-compose volumes on down
  fixtures/docker-compose/docker-compose-with-volume.yml
  src/docker-compose-environment.test.ts
  src/docker-compose-environment.ts
Labels: enhancement

#144 Add test for DockerCompose with healthcheck
  fixtures/docker-compose/docker-compose-with-healthcheck.yml
  src/docker-compose-environment.test.ts
  src/wait-strategy.ts
Labels: documentation

#146 feat: add elasticsearch module
  package-lock.json
  package.json
  src/index.ts
  src/modules/elasticsearch/README.md
  src/modules/elasticsearch/elasticsearch-container.test.ts
  src/modules/elasticsearch/elasticsearch-container.ts
Labels: enhancement, minor

#147 Fix Windows
  fixtures/docker-compose/docker-compose-with-healthcheck.yml
  fixtures/docker-compose/docker-compose-with-name.yml
  fixtures/docker-compose/docker-compose-with-network.yml
  fixtures/docker-compose/docker-compose-with-volume.yml
  fixtures/docker-compose/docker-compose.yml
  package-lock.json
  package.json
  src/container.ts
  src/docker-client.ts
  src/docker-compose-environment.test.ts
  src/docker-ignore.ts
  src/generic-container.ts
  src/reaper.ts
Labels: bug, enhancement, maintenance, minor

#151 Support disabling the ryuk container
  README.md
  src/docker-compose-environment.ts
  src/generic-container.ts
  src/network.ts
  src/reaper.ts
  src/repo-tag.test.ts
  src/repo-tag.ts
Labels: enhancement, minor

#153 Log wait strategy supports regex
  README.md
  src/generic-container.test.ts
  src/wait-strategy.ts
  src/wait.ts
Labels: enhancement, minor

#157 Remove dependency on node-duration
  README.md
  package-lock.json
  package.json
  src/container.ts
  src/docker-client.ts
  src/docker-compose-environment.ts
  src/generic-container.test.ts
  src/generic-container.ts
  src/modules/elasticsearch/elasticsearch-container.ts
  src/retry-strategy.ts
  src/test-container.ts
  src/wait-strategy.ts
Labels: enhancement, major
