Repository testcontainers/testcontainers-node, pull requests merged in 2021-09, with the labels that each got.

#267 Do not wait for public ports when upping docker-compose-environment
  fixtures/docker-compose/docker-compose-with-private-port.yml
  src/docker-compose-environment/docker-compose-environment.test.ts
  src/docker-compose-environment/docker-compose-environment.ts
Labels: bug, patch

#269 Better logging/throwing of DockerCompose errors
  src/docker-compose/functions/docker-compose-down.ts
  src/docker-compose/functions/docker-compose-stop.ts
  src/docker-compose/functions/docker-compose-up.ts
Labels: enhancement, patch

#274 Fix pull issue where image tag is sha256 digest
  src/docker-image-name.test.ts
  src/docker-image-name.ts
Labels: bug, patch

#277 Update deps
  package-lock.json
  package.json
  src/generic-container/generic-container.test.ts
Labels: maintenance, patch

#278 Update deps
  package-lock.json
  package.json
Labels: maintenance, patch

#280 Sonarlint fixes
  src/docker-compose-environment/docker-compose-environment.ts
  src/docker-ignore.ts
  src/docker/functions/container/remove-container.ts
  src/docker/functions/container/start-container.ts
  src/docker/get-docker-host.ts
  src/generic-container/started-generic-container.ts
  src/modules/abstract-started-container.ts
  src/modules/kafka/kafka-container.ts
  src/reaper.ts
  src/wait-strategy.ts
Labels: maintenance, patch

#282 adds mysql module
  package-lock.json
  package.json
  src/index.ts
  src/modules/mysql/README.md
  src/modules/mysql/mysql-container.test.ts
  src/modules/mysql/mysql-container.ts
Labels: enhancement, minor
