Repository testcontainers/testcontainers-node, pull requests merged in 2021-01, with the labels that each got.

#178 Fix incorrect parsing of image name
  src/docker-client.ts
  src/repo-tag.test.ts
  src/repo-tag.ts
Labels: bug, patch

#179 Load registry auth information
  .eslintrc.js
  README.md
  src/docker-client.ts
  src/docker-image-name.test.ts
  src/docker-image-name.ts
  src/generic-container.test.ts
  src/generic-container.ts
  src/modules/arangodb/arangodb-container.ts
  src/modules/elasticsearch/elasticsearch-container.ts
  src/modules/kafka/README.md
  src/modules/kafka/kafka-container.test.ts
  src/modules/kafka/kafka-container.ts
  src/modules/neo4j/neo4j-container.ts
  src/network.test.ts
  src/port-forwarder.ts
  src/pull-stream-parser.test.ts
  src/pull-stream-parser.ts
  src/reaper.ts
  src/registry-auth-locator/auths.test.ts
  src/registry-auth-locator/auths.ts
  src/registry-auth-locator/cred-helpers.test.ts
  src/registry-auth-locator/cred-helpers.ts
  src/registry-auth-locator/credential-provider.ts
  src/registry-auth-locator/creds-store.test.ts
  src/registry-auth-locator/creds-store.ts
  src/registry-auth-locator/index.ts
  src/registry-auth-locator/registry-auth-locator.ts
  src/registry-auth-locator/types.ts
  src/repo-tag.test.ts
  src/repo-tag.ts
  src/test-container.ts
Labels: enhancement, major

#182 Return empty `DockerConfig` if no `.docker/config.json` file
  src/registry-auth-locator/index.ts
Labels: bug, patch

#180 Add ability to copy files to a container before it is started
  README.md
  package-lock.json
  package.json
  src/container.ts
  src/generic-container.test.ts
  src/generic-container.ts
  src/test-container.ts
Labels: enhancement, minor

#183 Propagate a clear error when a container with LogWaitStrategy fails
  src/wait-strategy.ts
Labels: enhancement, minor
