Repository testcontainers/testcontainers-node, pull requests merged in 2021-07, with the labels that each got.

#221 Output daemon container logs
  src/container.ts
  src/docker-client.ts
  src/generic-container.test.ts
  src/generic-container.ts
  src/modules/kafka/kafka-container.test.ts
  src/port-forwarder.test.ts
Labels: enhancement, minor

#222 Increase Reaper socket verbosity
  src/logger.ts
  src/reaper.ts
Labels: enhancement, patch

#223 Use host-port wait strategy of the Reaper
  package-lock.json
  package.json
  src/generic-container.test.ts
  src/modules/kafka/kafka-container.ts
  src/port-binder.test.ts
  src/port-binder.ts
  src/port-client.test.ts
  src/port-client.ts
  src/port-forwarder.test.ts
  src/port-generator.test.ts
  src/port-generator.ts
  src/reaper.test.ts
  src/reaper.ts
  src/test-helper.ts
Labels: bug, patch

#224 Log system info for better diagnostics
  .github/workflows/node.js.yml
  package-lock.json
  package.json
  src/container.ts
  src/docker-client-instance.ts
  src/docker-client.ts
  src/generic-container.test.ts
  src/generic-container.ts
Labels: enhancement, patch

#227 Log docker-compose diagnostics
  src/docker-client-instance.ts
Labels: enhancement, patch

#229 Update dependencies
  README.md
  package-lock.json
  package.json
  src/generic-container.test.ts
  src/modules/neo4j/neo4j-container.test.ts
Labels: maintenance, patch

#231 Support running container as a user
  README.md
  src/docker-client-instance.ts
  src/docker-client.ts
  src/generic-container.test.ts
  src/generic-container.ts
  src/modules/neo4j/neo4j-container.test.ts
  src/test-container.ts
Labels: enhancement, minor

#233 Remove ContainerState class + minor improvements
  src/container-state.ts
  src/docker-compose-environment.ts
  src/generic-container.ts
  src/registry-auth-locator/auths.ts
  src/registry-auth-locator/credential-provider.ts
  src/wait-strategy.ts
Labels: maintenance, patch

#235 Get host from container gateway if running inside container and IPAM not available
  src/docker-client-instance.ts
  src/get-docker-host.test.ts
  src/get-docker-host.ts
  src/log-system-diagnostics.ts
  src/run-in-container.test.ts
  src/run-in-container.ts
  src/wait-strategy.ts
Labels: bug, minor

#237 Pull image if not exists
  src/run-in-container.ts
Labels: bug, patch

#236 Demux container logs
  src/container.ts
  src/generic-container.ts
  src/log-system-diagnostics.ts
  src/reaper.test.ts
  src/run-in-container.ts
Labels: enhancement, minor

#241 Add PostgreSQL module
  package-lock.json
  package.json
  src/index.ts
  src/modules/arangodb/README.md
  src/modules/elasticsearch/README.md
  src/modules/kafka/README.md
  src/modules/neo4j/README.md
  src/modules/postgresql/README.md
  src/modules/postgresql/postgresql-container.test.ts
  src/modules/postgresql/postgresql-container.ts
  src/reaper.test.ts
Labels: enhancement, minor

#242 Fix Windows build issues
  package.json
  src/docker-compose-environment/docker-compose-environment.test.ts
  src/docker/functions/container/attach-container.ts
  src/docker/functions/container/inspect-container.ts
  src/docker/functions/demux-stream.ts
  src/docker/functions/run-in-container.ts
  src/reaper.test.ts
  src/test-helper.ts
Labels: maintenance, patch

#243 Remove duplicate container logs on startup error
  src/docker-compose-environment/docker-compose-environment.ts
  src/generic-container/generic-container.ts
Labels: enhancement, patch

#244 Remove daemon mode
  src/docker/functions/run-in-container.ts
  src/generic-container/generic-container.ts
  src/port-forwarder.ts
  src/reaper.ts
Labels: enhancement, patch

#245 Refactor modules
  src/modules/arangodb/arangodb-container.test.ts
  src/modules/arangodb/arangodb-container.ts
  src/modules/elasticsearch/elasticsearch-container.test.ts
  src/modules/elasticsearch/elasticsearch-container.ts
  src/modules/kafka/kafka-container.test.ts
  src/modules/kafka/kafka-container.ts
  src/modules/neo4j/neo4j-container.test.ts
  src/modules/neo4j/neo4j-container.ts
  src/modules/postgresql/README.md
  src/modules/postgresql/postgresql-container.ts
Labels: maintenance, patch

#247 Hardcode module image tags + reduce test maxWorkers
  package.json
  src/docker/functions/run-in-container.ts
  src/modules/arangodb/arangodb-container.ts
  src/modules/neo4j/neo4j-container.ts
  src/port-forwarder.test.ts
  src/reaper.test.ts
  src/test-helper.ts
Labels: maintenance, minor

#246 Add link to CI badge
  README.md
Labels: maintenance, patch

#248 Fix docker-compose error not being object
  src/docker-compose/functions/docker-compose-down.ts
  src/docker-compose/functions/docker-compose-stop.ts
  src/docker-compose/functions/docker-compose-up.ts
Labels: bug, patch
