Repository testcontainers/testcontainers-node, pull requests merged in 2022-10, with the labels that each got.

#400 Implement setting entrypoint
  README.md
  src/docker/functions/container/create-container.ts
  src/generic-container/generic-container.test.ts
  src/generic-container/generic-container.ts
  src/test-container.ts
Labels: enhancement, minor

#401 Add options for docker-compose down
  README.md
  src/docker-compose-environment/docker-compose-environment.ts
  src/docker-compose-environment/started-docker-compose-environment.ts
  src/docker-compose-environment/stopped-docker-compose-environment.ts
  src/docker-compose/functions/docker-compose-down.ts
  src/docker-compose/functions/docker-compose-up.ts
  src/generic-container/started-generic-container.ts
  src/test-container.ts
Labels: enhancement, minor

#402 Implement setting cache when building an image
  README.md
  src/docker/functions/image/build-image.ts
  src/generic-container/generic-container-builder.ts
Labels: enhancement, minor

#404 Provide logger for container exec output
  README.md
  src/docker/functions/container/exec-container.ts
  src/logger.ts
  src/port-check.ts
Labels: enhancement, minor

#403 Implement setting ulimits and capabilities
  README.md
  fixtures/docker-compose/docker-compose-malformed.yml
  fixtures/docker-compose/docker-compose-with-env-file/docker-compose.yml
  fixtures/docker-compose/docker-compose-with-env.yml
  fixtures/docker-compose/docker-compose-with-healthcheck.yml
  fixtures/docker-compose/docker-compose-with-many-services.yml
  fixtures/docker-compose/docker-compose-with-name.yml
  fixtures/docker-compose/docker-compose-with-network.yml
  fixtures/docker-compose/docker-compose-with-override/docker-compose.yml
  fixtures/docker-compose/docker-compose-with-private-port.yml
  fixtures/docker-compose/docker-compose-with-profile.yml
  fixtures/docker-compose/docker-compose-with-volume.yml
  fixtures/docker-compose/docker-compose.yml
  fixtures/docker/docker/Dockerfile
  src/docker/functions/container/create-container.ts
  src/docker/functions/run-in-container.test.ts
  src/docker/types.ts
  src/generic-container/generic-container.test.ts
  src/generic-container/generic-container.ts
  src/network.test.ts
  src/port-forwarder.test.ts
  src/reaper.test.ts
  src/test-container.ts
Labels: enhancement, minor

#343 Support for health checks using CMD rather than CMD-SHELL
  README.md
  src/docker/functions/container/create-container.ts
  src/docker/types.ts
  src/generic-container/generic-container.test.ts
Labels: enhancement, major

#408 Define required node version
  .npmrc
  .nvmrc
  package-lock.json
  package.json
Labels: maintenance, major

#405 API updates
  .eslintrc.js
  .github/workflows/node.js.yml
  .npmrc
  .nvmrc
  README.md
  package-lock.json
  package.json
  src/bound-ports.ts
  src/docker-compose-environment/docker-compose-environment.test.ts
  src/docker-compose-environment/docker-compose-environment.ts
  src/docker-compose/default-docker-compose-options.ts
  src/docker-compose/docker-compose-options.ts
  src/docker/docker-client.ts
  src/docker/functions/container/container-logs.ts
  src/docker/functions/container/create-container.ts
  src/docker/functions/container/exec-container.ts
  src/docker/functions/container/get-container.ts
  src/docker/functions/container/inspect-container.ts
  src/docker/functions/image/build-image.ts
  src/docker/functions/image/pull-image.ts
  src/docker/functions/run-in-container.ts
  src/docker/types.ts
  src/generic-container/generic-container-builder.ts
  src/generic-container/generic-container.test.ts
  src/generic-container/generic-container.ts
  src/generic-container/started-generic-container.ts
  src/modules/abstract-started-container.ts
  src/modules/arangodb/arangodb-container.ts
  src/modules/elasticsearch/elasticsearch-container.ts
  src/modules/kafka/kafka-container.test.ts
  src/modules/kafka/kafka-container.ts
  src/modules/mongodb/mongodb-container.test.ts
  src/modules/mongodb/mongodb-container.ts
  src/modules/mysql/mysql-container.ts
  src/modules/nats/nats-container.test.ts
  src/modules/nats/nats-container.ts
  src/modules/neo4j/neo4j-container.ts
  src/modules/postgresql/postgresql-container.ts
  src/network.test.ts
  src/port-binder.ts
  src/port-check.test.ts
  src/port-check.ts
  src/port-forwarder.test.ts
  src/port-forwarder.ts
  src/port-generator.ts
  src/port.ts
  src/reaper.ts
  src/test-container.ts
  src/test-containers.ts
  src/wait-strategy.ts
  tsconfig.json
  tsconfig.prod.json
Labels: maintenance, major

#409 Extract waitForContainer to own module
  src/docker-compose-environment/docker-compose-environment.ts
  src/generic-container/generic-container.ts
  src/generic-container/started-generic-container.ts
  src/wait-for-container.ts
  src/wait-strategy.ts
Labels: maintenance, patch
