Repository testcontainers/testcontainers-node, pull requests merged in 2022-09, with the labels that each got.

#393 Move mongoose to dev dependencies
  package.json
Labels: enhancement, patch

#394 Fix Dockerode circular dependency when finding host through default gateway
  package-lock.json
  package.json
  src/docker/docker-client.ts
  src/docker/functions/container/attach-container.ts
  src/docker/functions/container/container-logs.ts
  src/docker/functions/demux-stream.ts
  src/docker/functions/get-info.ts
  src/docker/functions/image/image-exists.ts
  src/docker/functions/image/list-images.ts
  src/docker/functions/image/pull-image.ts
  src/docker/functions/run-in-container.ts
  src/generic-container/generic-container-builder.ts
  src/generic-container/generic-container.ts
  src/log-system-diagnostics.ts
  src/reaper.test.ts
Labels: bug, patch

#397 Improve diagnostic logging for HostPort wait strategy
  src/log-system-diagnostics.ts
  src/port-check.test.ts
  src/port-check.ts
Labels: enhancement, minor

#395 Pass Dockerode ExecStartOptions to StartedGenericContainer.exec
  package-lock.json
  src/docker/functions/container/exec-container.ts
  src/generic-container/started-generic-container.ts
  src/port-check.ts
  src/test-container.ts
Labels: enhancement, minor
