Repository testcontainers/testcontainers-node, pull requests merged in 2022-04, with the labels that each got.

#338 Use log wait strategy for resource reaper
  package-lock.json
  src/docker/docker-client.ts
  src/reaper.ts
Labels: maintenance, minor

#345 Create template for bug reports
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: maintenance

#347 feat: add `withLabel`
  README.md
  src/docker/functions/container/create-container.ts
  src/docker/functions/container/inspect-container.ts
  src/docker/functions/create-labels.ts
  src/docker/types.ts
  src/generic-container/generic-container.test.ts
  src/generic-container/generic-container.ts
  src/generic-container/started-generic-container.ts
  src/modules/abstract-started-container.ts
  src/test-container.ts
Labels: enhancement, minor

#350 Update non ESM deps major
  package-lock.json
  package.json
  src/docker-compose/functions/docker-compose-down.ts
  src/docker-compose/functions/docker-compose-stop.ts
  src/docker-compose/functions/docker-compose-up.ts
  src/docker/functions/container/stop-container.ts
  tsconfig.json
Labels: maintenance, patch

#352 fix: make kafka containers reusable
  src/modules/kafka/kafka-container.test.ts
  src/modules/kafka/kafka-container.ts
Labels: bug, patch

#355 Update patch dependencies
  package-lock.json
  package.json
  src/modules/elasticsearch/elasticsearch-container.test.ts
Labels: maintenance, patch

#354 feat: expose method to setup a SASL_SSL listener in a Kafka container
  package-lock.json
  src/modules/kafka/kafka-container.test.ts
  src/modules/kafka/kafka-container.ts
  src/modules/kafka/test-certs/Dockerfile
  src/modules/kafka/test-certs/README.md
  src/modules/kafka/test-certs/generate-certs.sh
  src/modules/kafka/test-certs/kafka.client.truststore.pem
  src/modules/kafka/test-certs/kafka.server.keystore.pfx
  src/modules/kafka/test-certs/kafka.server.truststore.pfx
  tsconfig.json
Labels: enhancement, minor

#357 feat: add support for specifying host port on module container instan…
  package-lock.json
  src/generic-container/generic-container.ts
  src/modules/arangodb/arangodb-container.ts
  src/modules/elasticsearch/elasticsearch-container.ts
  src/modules/mysql/mysql-container.ts
  src/modules/neo4j/neo4j-container.ts
  src/modules/postgresql/postgresql-container.ts
Labels: enhancement, minor

#360 Fix `DockerClient` `ConfigurationStrategy` when `DOCKER_HOST` is a socket path
  package-lock.json
  package.json
  src/docker/docker-client.ts
Labels: bug, patch
