Repository testcontainers/testcontainers-node, pull requests merged in 2023-07, with the labels that each got.

#592 Fix for Windows Dockerfile parsing
  fixtures/docker-compose/docker-compose-with-healthcheck-with-start-period.yml
  fixtures/docker/docker-with-health-check-with-start-period/Dockerfile
  src/docker-compose-environment/docker-compose-environment.test.ts
  src/dockerfile-parser.ts
  src/reaper.test.ts
  src/uuid.ts
Labels: bug, patch

#598 Add HiveMQ module
  docs/modules/hivemq.md
  mkdocs.yml
  package-lock.json
  package.json
  src/index.ts
  src/modules/hivemq/hivemq-container.test.ts
  src/modules/hivemq/hivemq-container.ts
Labels: enhancement, minor

#599 Selenium tests work with ARM + Retry for flaky CI
  src/modules/selenium/selenium-container.test.ts
Labels: maintenance, patch

#603 Update dependency minor versions
  package-lock.json
  package.json
Labels: maintenance, patch

#604 Specify mode when copying files/content to a container
  docs/features/containers.md
  src/docker/types.ts
  src/generic-container/generic-container.test.ts
  src/generic-container/generic-container.ts
Labels: enhancement, minor

#606 Support copying directories to a container
  docs/features/containers.md
  src/docker/types.ts
  src/generic-container/generic-container.test.ts
  src/generic-container/generic-container.ts
  src/test-container.ts
Labels: enhancement, minor

#597 Create a single Reaper session per parallel test run
  package-lock.json
  package.json
  src/docker-compose-environment/docker-compose-environment.ts
  src/docker/client/docker-client-types.ts
  src/docker/client/docker-client.ts
  src/docker/client/strategy/configuration-strategy.ts
  src/docker/client/strategy/docker-client-strategy.ts
  src/docker/client/strategy/npipe-socket-strategy.ts
  src/docker/client/strategy/rootless-unix-socket-strategy.ts
  src/docker/client/strategy/testcontainers-host-strategy.ts
  src/docker/client/strategy/unix-socket-strategy.ts
  src/docker/functions/container/create-container.ts
  src/docker/functions/create-labels.test.ts
  src/docker/functions/create-labels.ts
  src/docker/functions/image/build-image.ts
  src/docker/functions/network/create-network.ts
  src/docker/remote-docker-unix-socket-path.test.ts
  src/docker/remote-docker-unix-socket-path.ts
  src/docker/session-id.ts
  src/file-lock.ts
  src/generic-container/generic-container-builder.ts
  src/generic-container/generic-container.ts
  src/network.ts
  src/port-forwarder.ts
  src/reaper.test.ts
  src/reaper.ts
  src/test-helper.ts
  src/wait-strategy/host-port-wait-strategy.test.ts
Labels: enhancement, minor

#608 Support excluding a build image from cleanup by Ryuk
  docs/features/images.md
  src/docker/functions/image/build-image.ts
  src/generic-container/generic-container-builder.ts
  src/generic-container/generic-container-dockerfile.test.ts
  src/index.ts
  src/test-helper.ts
Labels: enhancement, minor

#609 Selenium additionally wait for listening ports
  src/modules/selenium/selenium-container.ts
Labels: maintenance, patch

#611 Fix race condition where messages are lost between log consumers
  src/generic-container/generic-container.ts
Labels: bug, patch

#614 Support copying directories to a started container
  docs/features/containers.md
  src/generic-container/generic-container.test.ts
  src/generic-container/started-generic-container.ts
  src/modules/abstract-started-container.ts
  src/test-container.ts
Labels: enhancement, minor

#612 Await Selenium WebDriver creation in tests
  docs/modules/selenium.md
  src/generic-container/generic-container.test.ts
  src/modules/selenium/selenium-container.test.ts
  src/wait-strategy/composite-wait-strategy.ts
  src/wait-strategy/health-check-wait-strategy.ts
  src/wait-strategy/host-port-wait-strategy.ts
  src/wait-strategy/http-wait-strategy.ts
  src/wait-strategy/log-wait-strategy.ts
  src/wait-strategy/shell-wait-strategy.ts
Labels: maintenance, patch

#620 Automatic fallback to docker-compose v2
  src/docker-compose-environment/docker-compose-environment.ts
  src/docker-compose-environment/started-docker-compose-environment.ts
  src/docker-compose-environment/stopped-docker-compose-environment.ts
  src/docker-compose/container-name-resolver.test.ts
  src/docker-compose/container-name-resolver.ts
  src/docker-compose/default-docker-compose-options.ts
  src/docker-compose/docker-compose-client.ts
  src/docker-compose/docker-compose-options.ts
  src/docker-compose/functions/docker-compose-down.ts
  src/docker-compose/functions/docker-compose-pull.ts
  src/docker-compose/functions/docker-compose-stop.ts
  src/docker-compose/functions/docker-compose-up.ts
  src/docker/client/docker-client-types.ts
  src/docker/client/docker-client.ts
  src/system-info.ts
  src/test-container.ts
Labels: enhancement, minor

#622 Fix extra backtick in docs
  docs/features/containers.md
Labels: maintenance, patch
