Repository testcontainers/testcontainers-node, pull requests merged in 2023-05, with the labels that each got.

#559 Add withLogConsumer + general logging improvements
  docs/configuration.md
  docs/features/containers.md
  src/docker-compose-environment/docker-compose-environment.ts
  src/docker-compose/default-docker-compose-options.ts
  src/docker-compose/docker-compose-options.ts
  src/docker-compose/functions/docker-compose-down.ts
  src/docker-compose/functions/docker-compose-pull.ts
  src/docker-compose/functions/docker-compose-stop.ts
  src/docker-compose/functions/docker-compose-up.ts
  src/docker/docker-client-config.ts
  src/docker/docker-client.ts
  src/docker/functions/container/attach-container.ts
  src/docker/functions/container/create-container.ts
  src/docker/functions/container/exec-container.ts
  src/docker/functions/container/get-container.ts
  src/docker/functions/container/inspect-container.ts
  src/docker/functions/container/put-container-archive.ts
  src/docker/functions/container/remove-container.ts
  src/docker/functions/container/restart-container.ts
  src/docker/functions/container/start-container.ts
  src/docker/functions/container/stop-container.ts
  src/docker/functions/image/build-image.ts
  src/docker/functions/image/pull-image.ts
  src/docker/functions/network/connect-network.ts
  src/docker/functions/network/create-network.ts
  src/docker/functions/network/remove-network.ts
  src/docker/functions/run-in-container.ts
  src/docker/pull-stream-parser.ts
  src/docker/resolve-host.ts
  src/generic-container/generic-container-builder.ts
  src/generic-container/generic-container-logs.test.ts
  src/generic-container/generic-container.ts
  src/generic-container/started-generic-container.ts
  src/logger.ts
  src/network.ts
  src/port-check.test.ts
  src/port-check.ts
  src/port-forwarder.ts
  src/reaper.ts
  src/registry-auth-locator/credential-provider.ts
  src/registry-auth-locator/get-auth-config.ts
  src/system-info.ts
  src/test-container.ts
  src/uuid.ts
  src/wait-for-container.ts
  src/wait-strategy/composite-wait-strategy.ts
  src/wait-strategy/health-check-wait-strategy.ts
  src/wait-strategy/host-port-wait-strategy.ts
  src/wait-strategy/http-wait-strategy.test.ts
  src/wait-strategy/http-wait-strategy.ts
  src/wait-strategy/log-wait-strategy.ts
  src/wait-strategy/shell-wait-strategy.ts
  src/wait-strategy/startup-check-strategy.test.ts
  src/wait-strategy/startup-check-strategy.ts
Labels: enhancement, minor

#560 Supported container runtimes tidy up
  docs/supported-container-runtimes.md
Labels: maintenance, patch

#566 General refactoring
  src/docker-compose-environment/docker-compose-environment.ts
  src/docker-compose/default-docker-compose-options.ts
  src/docker/client/docker-client-config.ts
  src/docker/client/docker-client.ts
  src/docker/client/strategy/configuration-strategy.ts
  src/docker/client/strategy/docker-client-strategy.ts
  src/docker/client/strategy/npipe-socket-strategy.ts
  src/docker/client/strategy/rootless-unix-socket-strategy.ts
  src/docker/client/strategy/unix-socket-strategy.ts
  src/docker/functions/container/container-logs.ts
  src/docker/functions/container/create-container.ts
  src/docker/functions/container/exec-container.ts
  src/docker/functions/container/get-container.ts
  src/docker/functions/container/list-containers.ts
  src/docker/functions/image/build-image.ts
  src/docker/functions/network/connect-network.ts
  src/docker/functions/network/create-network.ts
  src/docker/functions/network/remove-network.ts
  src/docker/functions/run-in-container.test.ts
  src/docker/resolve-host.test.ts
  src/docker/resolve-host.ts
  src/docker/types.ts
  src/generic-container/generic-container-builder.ts
  src/generic-container/generic-container.ts
  src/generic-container/started-generic-container.ts
  src/port-check.ts
  src/port-forwarder.ts
  src/reaper.ts
  src/test-helper.ts
  src/wait-strategy/host-port-wait-strategy.ts
  src/wait-strategy/http-wait-strategy.ts
  src/wait-strategy/shell-wait-strategy.ts
  src/wait-strategy/startup-check-strategy.ts
Labels: maintenance, patch

#564 Add support for Testcontainers Host
  src/docker/client/docker-client-config.test.ts
  src/docker/client/docker-client-config.ts
  src/docker/client/docker-client.ts
  src/docker/client/strategy/configuration-strategy.ts
  src/docker/client/strategy/npipe-socket-strategy.ts
  src/docker/client/strategy/rootless-unix-socket-strategy.ts
  src/docker/client/strategy/testcontainers-host-strategy.test.ts
  src/docker/client/strategy/testcontainers-host-strategy.ts
  src/docker/client/strategy/unix-socket-strategy.ts
  src/docker/remote-docker-unix-socket-path.test.ts
  src/docker/remote-docker-unix-socket-path.ts
  src/docker/resolve-host.test.ts
  src/docker/resolve-host.ts
  src/port-check.ts
  src/reaper.ts
Labels: enhancement, minor

#569 Revert "Set host port to empty string (#550)"
  src/docker/functions/container/create-container.ts
Labels: bug, patch

#572 Cache Docker client config lookup
  src/docker/client/docker-client-config.test.ts
  src/docker/client/docker-client-config.ts
Labels: enhancement, minor

#553 Adding mysql connection uri utility function
  docs/modules/mysql.md
  src/modules/mysql/mysql-container.test.ts
  src/modules/mysql/mysql-container.ts
Labels: enhancement, minor

#573 Update podman mac run instructions
  docs/supported-container-runtimes.md
Labels: maintenance, patch

#574 Update ryuk to 0.5.1
  docs/configuration.md
  src/images.ts
Labels: maintenance, patch
