Repository testcontainers/testcontainers-node, pull requests merged in 2023-03, with the labels that each got.

#483 Select Docker host port binding according to resolved host IP family
  src/bound-ports.test.ts
  src/bound-ports.ts
  src/docker-compose-environment/docker-compose-environment.ts
  src/docker/docker-client.ts
  src/docker/functions/container/inspect-container.ts
  src/docker/lookup-host-ips.test.ts
  src/docker/lookup-host-ips.ts
  src/docker/types.ts
  src/generic-container/generic-container.ts
  src/generic-container/started-generic-container.ts
  src/port-binder.test.ts
  src/port-binder.ts
  src/port.test.ts
  src/port.ts
Labels: bug, patch

#466 Make sure container logs are output after container restart
  jest.config.js
  src/docker-compose-environment/docker-compose-environment.ts
  src/docker/functions/container/container-logs.ts
  src/docker/lookup-host-ips.test.ts
  src/generic-container/generic-container.test.ts
  src/generic-container/generic-container.ts
  src/generic-container/started-generic-container.ts
  src/port-check.test.ts
  src/wait-strategy.ts
Labels: bug, patch

#484 Do not return auth config when registry names partially match
  jest.config.js
  src/registry-auth-locator/auths.test.ts
  src/registry-auth-locator/auths.ts
  src/registry-auth-locator/credential-provider.test.ts
  src/registry-auth-locator/credential-provider.ts
  src/registry-auth-locator/registry-matches.test.ts
  src/registry-auth-locator/registry-matches.ts
Labels: maintenance, minor

#485 Fixes for consistent IPv4/IPv6 host resolution
  src/docker/lookup-host-ips.ts
Labels: bug, patch

#489 Fix run in container flakiness
  src/docker/functions/run-in-container.ts
  src/stream-utils.ts
Labels: bug, patch

#488 Fix container logs after restart flakiness
  .github/workflows/test-main.yml
  .github/workflows/test.yml
  package.json
  src/docker-compose-environment/docker-compose-environment.ts
  src/docker/functions/container/container-logs.ts
  src/generic-container/generic-container.ts
  src/generic-container/started-generic-container.ts
  src/wait-for-container.ts
  src/wait-strategy.ts
Labels: bug, patch

#486 Add support for rootless Docker
  .github/workflows/test-main.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/docker/docker-client.ts
  src/docker/get-remote-docker-unix-socket-path.test.ts
  src/docker/get-remote-docker-unix-socket-path.ts
  src/docker/rootless-unix-socket-strategy.test.ts
  src/docker/rootless-unix-socket-strategy.ts
  src/generic-container/generic-container.test.ts
  src/modules/mysql/mysql-container.ts
  src/reaper.ts
  src/type-guards.ts
Labels: enhancement, minor

#493 Add support for getting first mapped port
  docs/features/containers.md
  src/bound-ports.test.ts
  src/bound-ports.ts
  src/generic-container/generic-container.test.ts
  src/generic-container/started-generic-container.ts
  src/modules/abstract-started-container.ts
  src/test-container.ts
Labels: enhancement, minor

#492 Docker compose container names depend on version
  src/docker-compose-environment/docker-compose-environment.test.ts
  src/reaper.test.ts
  src/system-info.ts
  src/test-helper.ts
Labels: maintenance, patch

#497 Fix for handling Docker daemon ping response due to docker-modem change
  package-lock.json
  package.json
  src/docker/docker-client.ts
Labels: bug, patch

#482 Add support for TCC turbo mode
  package-lock.json
  package.json
  src/docker/docker-client.ts
  src/docker/functions/image/build-image.ts
  src/modules/arangodb/arangodb-container.ts
  src/modules/mysql/mysql-container.ts
  src/modules/nats/nats-container.ts
  src/modules/neo4j/neo4j-container.ts
  src/modules/postgresql/postgresql-container.ts
  src/uuid.ts
Labels: enhancement, minor

#499 Windows fixes
  src/docker/docker-client.ts
  src/system-info.ts
Labels: bug, patch

#494 Fix issue with `DOCKER_HOST` and add limited Podman CI workflow
  .github/workflows/test-main.yml
  .github/workflows/test.yml
  fixtures/docker/docker-with-health-check/Dockerfile
  src/docker/docker-client-config.test.ts
  src/docker/docker-client-config.ts
  src/docker/docker-client.ts
  src/docker/functions/get-info.ts
  src/docker/functions/image/build-image.ts
  src/generic-container/generic-container-builder.ts
  src/generic-container/generic-container.test.ts
  src/port.test.ts
  src/port.ts
  src/test-helper.ts
  src/testcontainers-properties-file.test.ts
  src/testcontainers-properties-file.ts
Labels: enhancement, minor

#502 Document how to create a custom container
  docs/features/containers.md
  src/index.ts
  src/modules/abstract-started-container.ts
Labels: maintenance, patch

#503 Refactor resolving host
  src/docker/docker-client.ts
  src/docker/resolve-host.test.ts
  src/docker/resolve-host.ts
Labels: maintenance, patch

#505 Remove private registry acceptance tests
  .github/workflows/test-main.yml
  .github/workflows/test.yml
  fixtures/docker/docker-private-multistage/Dockerfile
  fixtures/docker/docker-private/Dockerfile
  src/generic-container/generic-container.test.ts
Labels: maintenance, patch

#506 Reduce concurrent builds
  .github/workflows/test.yml
Labels: maintenance, patch

#513 Do not run CI for changes to docs
  .github/workflows/test-main.yml
  .github/workflows/test.yml
  docs/features/containers.md
Labels: maintenance, patch

#514 Split GenericContainer tests to run faster
  src/generic-container/generic-container-dockerfile.test.ts
  src/generic-container/generic-container-logs.test.ts
  src/generic-container/generic-container-network.test.ts
  src/generic-container/generic-container-resources-quota.test.ts
  src/generic-container/generic-container-restart.test.ts
  src/generic-container/generic-container-reuse.test.ts
  src/generic-container/generic-container-wait-strategies.test.ts
  src/generic-container/generic-container.test.ts
Labels: maintenance, patch

#516 Update minor deps
  package-lock.json
  package.json
Labels: maintenance, patch

#518 Add logs info to configuration doc
  docs/configuration.md
Labels: maintenance, patch
