Repository testcontainers/testcontainers-node, pull requests merged in 2023-11, with the labels that each got.

#675 Retire Node 16 (End-of-life) from CI
  .github/workflows/test.yml
Labels: maintenance

#644 Export container runtime
  docs/features/advanced.md
  mkdocs.yml
  packages/testcontainers/src/index.ts
Labels: enhancement, minor

#663 Allow to start containers with raw image IDs
  packages/testcontainers/src/container-runtime/image-name.test.ts
  packages/testcontainers/src/container-runtime/image-name.ts
Labels: enhancement, minor

#670 Add support for fetching container logs from a given time
  docs/features/containers.md
  packages/testcontainers/src/generic-container/abstract-started-container.ts
  packages/testcontainers/src/generic-container/generic-container-logs.test.ts
  packages/testcontainers/src/generic-container/started-generic-container.ts
  packages/testcontainers/src/test-container.ts
Labels: enhancement, minor

#668 Add support for setting `user`, `workingDir` and `env` when executing a command in a container
  docs/features/containers.md
  packages/testcontainers/src/container-runtime/clients/container/container-client.ts
  packages/testcontainers/src/container-runtime/clients/container/docker-container-client.ts
  packages/testcontainers/src/container-runtime/clients/container/podman-container-client.ts
  packages/testcontainers/src/container-runtime/clients/container/types.ts
  packages/testcontainers/src/generic-container/abstract-started-container.ts
  packages/testcontainers/src/generic-container/generic-container.test.ts
  packages/testcontainers/src/generic-container/started-generic-container.ts
  packages/testcontainers/src/index.ts
  packages/testcontainers/src/test-container.ts
  packages/testcontainers/src/types.ts
Labels: enhancement, minor

#679 Export `@types/dockerode` as a dependency
  package-lock.json
  packages/testcontainers/package.json
Labels: bug, patch

#680 Reuse PortForwarder container if it is running
  packages/testcontainers/src/port-forwarder/port-forwarder.test.ts
  packages/testcontainers/src/port-forwarder/port-forwarder.ts
  packages/testcontainers/src/reaper/reaper.ts
  packages/testcontainers/src/test-containers.ts
  packages/testcontainers/src/utils/labels.ts
Labels: bug, patch

#681 Switch docker compose defaults from v1 to v2
  packages/testcontainers/src/container-runtime/clients/compose/compose-client.ts
Labels: enhancement, minor
