Repository testcontainers/testcontainers-node, pull requests merged in 2023-08, with the labels that each got.

#624 Replace variable value with constant
  src/modules/postgresql/src/postgresql-container.ts
Labels: maintenance, patch

#626 Exclude test-helper from package
  src/testcontainers/tsconfig.build.json
Labels: maintenance, patch

#627 Improve test coverage of container runtime strategies
  src/modules/hivemq/src/hivemq-container.ts
  src/testcontainers/src/container-runtime/clients/client.ts
  src/testcontainers/src/container-runtime/clients/container/docker-container-client.ts
  src/testcontainers/src/container-runtime/strategies/configuration-strategy.test.ts
  src/testcontainers/src/container-runtime/strategies/configuration-strategy.ts
  src/testcontainers/src/container-runtime/strategies/npipe-socket-strategy.test.ts
  src/testcontainers/src/container-runtime/strategies/npipe-socket-strategy.ts
  src/testcontainers/src/container-runtime/strategies/unix-socket-strategy.test.ts
  src/testcontainers/src/container-runtime/strategies/unix-socket-strategy.ts
Labels: maintenance, patch

#628 Add support for targeting a build stage when building a Docker image
  docs/features/images.md
  src/testcontainers/fixtures/docker/docker-multi-stage/Dockerfile
  src/testcontainers/src/generic-container/generic-container-builder.ts
  src/testcontainers/src/generic-container/generic-container.test.ts
Labels: enhancement, minor

#630 Copy README and LICENSE from root to each package on pack
  .gitignore
  package-lock.json
  package.json
  src/modules/arangodb/package.json
  src/modules/elasticsearch/package.json
  src/modules/hivemq/package.json
  src/modules/kafka/package.json
  src/modules/mongodb/package.json
  src/modules/mysql/package.json
  src/modules/nats/package.json
  src/modules/neo4j/package.json
  src/modules/postgresql/package.json
  src/modules/selenium/package.json
Labels: maintenance, patch

#634 Rename Elastic Search to Elasticsearch in docs
  docs/modules/elasticsearch.md
  mkdocs.yml
Labels: patch, documentation

#632 Restructure test workflow
  .github/workflows/npm-publish.yml
  .github/workflows/test-main.yml
  .github/workflows/test-template.yml
  .github/workflows/test.yml
  README.md
Labels: maintenance, patch

#635 Remove unnecessary ping of container runtime
  packages/testcontainers/src/container-runtime/clients/client.ts
  packages/testcontainers/src/container-runtime/clients/container/container-client.ts
  packages/testcontainers/src/container-runtime/clients/container/docker-container-client.ts
  packages/testcontainers/src/container-runtime/strategies/utils/config.ts
Labels: enhancement, minor

#636 Update `DOCKER_AUTH_CONFIG` example in docs
  docs/configuration.md
Labels: documentation

#638 Update minor deps
  package-lock.json
  package.json
  packages/modules/mongodb/package.json
  packages/modules/mysql/package.json
  packages/modules/neo4j/package.json
  packages/modules/postgresql/package.json
  packages/modules/selenium/package.json
Labels: maintenance, patch

#637 Add UA header to Docker runtime
  packages/testcontainers/src/container-runtime/clients/client.ts
Labels: maintenance, minor

#639 Fix Npipe strategy discovery for Windows
  packages/testcontainers/src/container-runtime/strategies/npipe-socket-strategy.test.ts
  packages/testcontainers/src/container-runtime/strategies/npipe-socket-strategy.ts
Labels: bug, patch
