Repository testcontainers/testcontainers-node, pull requests merged in 2023-02, with the labels that each got.

#443 fix: custom labels on reusable generic containers
  src/generic-container/generic-container.test.ts
  src/generic-container/generic-container.ts
Labels: bug, patch

#450 fix: correctly evaluate predicates in HttpWaitStrategy
  src/http-wait-strategy.test.ts
  src/http-wait-strategy.ts
  src/retry-strategy.ts
Labels: bug, patch

#447 fix: make sure log based waiting strategy respects container restarts
  src/docker/functions/container/container-logs.ts
  src/docker/functions/container/inspect-container.ts
  src/generic-container/generic-container.test.ts
  src/wait-strategy.ts
Labels: bug, patch

#449 fix: make sure to not create more than one reusable container
  package-lock.json
  package.json
  src/generic-container/generic-container.test.ts
  src/generic-container/generic-container.ts
Labels: bug, patch

#451 Update patch dependencies
  package-lock.json
  package.json
Labels: maintenance, patch

#414 Update ryuk and sshd version images
  README.md
  src/images.ts
  src/port-forwarder.ts
Labels: maintenance, minor

#463 Check and report on test coverage in pipeline
  .github/workflows/node.js.yml
  .github/workflows/test-master.yml
  .github/workflows/test.yml
  .gitignore
  azure-pipelines.yml
  jest.config.js
  package.json
Labels: maintenance, patch

#461 Add code linting to pipeline
  .eslintrc.js
  .github/workflows/lint.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/docker-compose/functions/docker-compose-down.ts
  src/docker-compose/functions/docker-compose-stop.ts
  src/docker-compose/functions/docker-compose-up.ts
  src/docker/docker-client.ts
  src/docker/functions/container/restart-container.ts
  src/docker/functions/container/stop-container.ts
  src/docker/functions/image/build-image.ts
  src/registry-auth-locator/credential-provider.test.ts
  src/startup-check-strategy.ts
  src/test-container.ts
Labels: maintenance, patch

#458 Do not start ryuk for a reusable container
  src/generic-container/generic-container.ts
  src/reaper.test.ts
Labels: enhancement, minor

#456 UnixSocketStrategy should not use docker host from configuration file
  src/docker-compose/default-docker-compose-options.ts
  src/docker-compose/docker-compose.ts
  src/docker-compose/functions/docker-compose-down.ts
  src/docker-compose/functions/docker-compose-stop.ts
  src/docker-compose/functions/docker-compose-up.ts
  src/docker/docker-client.ts
  src/log-system-diagnostics.ts
  src/testcontainers-properties-file.test.ts
  src/testcontainers-properties-file.ts
Labels: bug, minor

#454 Set default container labels
  .github/workflows/test-master.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  smoke-test.js
  smoke-test.mjs
  src/docker/functions/container/get-container.ts
  src/docker/functions/create-labels.test.ts
  src/docker/functions/create-labels.ts
  src/generic-container/generic-container.test.ts
  src/generic-container/generic-container.ts
  src/labels.ts
  src/reaper.ts
  tsconfig.json
Labels: maintenance, minor

#469 Attempt to fix sonar test coverage
  sonar-project.properties
Labels: maintenance, patch

#471 Create devcontainer
  .devcontainer/devcontainer.json
  README.md
Labels: maintenance, patch

#470 Migrate README to mkdocs
  LICENSE
  README.md
  docker-compose.yml
  docs/configuration.md
  docs/features/compose.md
  docs/features/containers.md
  docs/features/images.md
  docs/features/networking.md
  docs/features/wait-strategies.md
  docs/index.md
  docs/modules/arangodb.md
  docs/modules/elastic-search.md
  docs/modules/kafka.md
  docs/modules/mongodb.md
  docs/modules/mysql.md
  docs/modules/nats.md
  docs/modules/neo4j.md
  docs/modules/postgresql.md
  docs/quickstart.md
  docs/site/community-logos/github.svg
  docs/site/community-logos/slack.svg
  docs/site/community-logos/stackoverflow.svg
  docs/site/community-logos/twitter.svg
  docs/site/css/extra.css
  docs/site/favicon.ico
  docs/site/language-logos/dotnet.svg
  docs/site/language-logos/go.svg
  docs/site/language-logos/java.svg
  docs/site/language-logos/nodejs.svg
  docs/site/language-logos/python.svg
  docs/site/language-logos/rust.svg
  docs/site/logo.png
  docs/site/logo.svg
  docs/site/theme/main.html
  docs/site/theme/partials/nav.html
  mkdocs.yml
  package.json
  requirements.txt
  runtime.txt
  src/modules/arangodb/arangodb-container.test.ts
  src/modules/elasticsearch/README.md
  src/modules/elasticsearch/elasticsearch-container.test.ts
  src/modules/kafka/README.md
  src/modules/kafka/kafka-container.test.ts
  src/modules/mongodb/README.md
  src/modules/mongodb/mongodb-container.test.ts
  src/modules/mysql/README.md
  src/modules/mysql/mysql-container.test.ts
  src/modules/nats/README.md
  src/modules/nats/nats-container.test.ts
  src/modules/neo4j/README.md
  src/modules/neo4j/neo4j-container.test.ts
  src/modules/postgresql/README.md
  src/modules/postgresql/postgresql-container.test.ts
Labels: maintenance, patch

#473 Rename master branch to main
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/npm-publish.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test-main.yml
  .github/workflows/test.yml
  README.md
  docs/index.md
  mkdocs.yml
Labels: maintenance, patch

#453 refactor: performance improvements
  src/docker/functions/container/exec-container.ts
  src/docker/functions/image/image-exists.ts
  src/docker/functions/image/pull-image.ts
  src/generic-container/generic-container.ts
  src/log-system-diagnostics.ts
  src/logger.ts
  src/port-check.test.ts
  src/port-check.ts
Labels: enhancement, minor

#474 Parse Dockerfile images containing build args
  fixtures/docker/dockerfile-parser/buildargs.Dockerfile
  src/dockerfile-parser.test.ts
  src/dockerfile-parser.ts
  src/generic-container/generic-container-builder.ts
Labels: bug, patch

#476 Add support for DOCKER_AUTH_CONFIG
  docs/configuration.md
  src/docker/functions/image/pull-image.ts
  src/generic-container/generic-container-builder.ts
  src/registry-auth-locator/get-auth-config.test.ts
  src/registry-auth-locator/get-auth-config.ts
Labels: enhancement, minor
