Repository testcontainers/testcontainers-node, pull requests merged in 2023-06, with the labels that each got.

#578 Add Selenium WebDriver module
  docs/features/containers.md
  docs/modules/selenium.md
  mkdocs.yml
  package-lock.json
  package.json
  src/docker/functions/container/create-container.ts
  src/docker/functions/container/get-container-archive.ts
  src/generic-container/generic-container.ts
  src/generic-container/started-generic-container.ts
  src/generic-container/stopped-generic-container.ts
  src/index.ts
  src/modules/abstract-started-container.ts
  src/modules/abstract-stopped-container.ts
  src/modules/selenium/selenium-container.test.ts
  src/modules/selenium/selenium-container.ts
  src/test-container.ts
Labels: enhancement, minor

#584 Update docker-compose to 0.24.1
  package-lock.json
  package.json
Labels: maintenance, minor

#587 Update java docs domain
  README.md
  docs/index.md
Labels: maintenance, patch

#586 Document how to use Selenium on ARM architectures
  docs/modules/selenium.md
Labels: maintenance, patch

#585 Do not crash when Docker client strategy throws error
  src/docker/client/docker-client.ts
Labels: bug, minor

#589 Allow both string and string[] for container exec command
  src/docker-compose-environment/docker-compose-environment.test.ts
  src/generic-container/started-generic-container.ts
  src/modules/abstract-started-container.ts
  src/test-container.ts
Labels: enhancement, minor

#588 Fix Kafka SASL_SSL listener inside Docker network
  src/modules/kafka/kafka-container.test.ts
  src/modules/kafka/kafka-container.ts
Labels: bug, patch

#591 Update dependency minor versions
  package-lock.json
  package.json
Labels: maintenance, patch

#595 Add windows-test slash command
  .github/workflows/windows-test-command-dispatch.yml
  .github/workflows/windows-test.yml
Labels: maintenance, patch
