Repository testcontainers/testcontainers-node, pull requests merged in 2024-11, with the labels that each got.

#851 Add MariaDB module
  docs/modules/mariadb.md
  mkdocs.yml
  package-lock.json
  packages/modules/mariadb/jest.config.ts
  packages/modules/mariadb/package.json
  packages/modules/mariadb/src/index.ts
  packages/modules/mariadb/src/mariadb-container.test.ts
  packages/modules/mariadb/src/mariadb-container.ts
  packages/modules/mariadb/tsconfig.build.json
  packages/modules/mariadb/tsconfig.json
Labels: enhancement, minor

#856 Revert HealthCheckWaitStrategy poll
  packages/testcontainers/src/wait-strategies/health-check-wait-strategy.ts
Labels: bug, patch

#854 CI: update Actions versions from 3 -> 4
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/npm-publish.yml
  .github/workflows/test-template.yml
  .github/workflows/test.yml
  .github/workflows/windows-test-command-dispatch.yml
  .github/workflows/windows-test.yml
Labels: maintenance, patch

#855 Add Cassandra module
  docs/modules/cassandra.md
  mkdocs.yml
  package-lock.json
  packages/modules/cassandra/jest.config.ts
  packages/modules/cassandra/package.json
  packages/modules/cassandra/src/cassandra-container.test.ts
  packages/modules/cassandra/src/cassandra-container.ts
  packages/modules/cassandra/src/index.ts
  packages/modules/cassandra/tsconfig.build.json
  packages/modules/cassandra/tsconfig.json
Labels: enhancement, minor

#858 Add Node 22 to CI version matrix
  .github/workflows/lint.yml
  .github/workflows/npm-publish.yml
  .github/workflows/test.yml
Labels: maintenance, patch

#860 Add Azurite module
  docs/modules/azurite.md
  mkdocs.yml
  package-lock.json
  packages/modules/azurite/jest.config.ts
  packages/modules/azurite/package.json
  packages/modules/azurite/src/azurite-container.test.ts
  packages/modules/azurite/src/azurite-container.ts
  packages/modules/azurite/src/index.ts
  packages/modules/azurite/tsconfig.build.json
  packages/modules/azurite/tsconfig.json
Labels: enhancement, minor

#861 Add ScyllaDB module
  docs/modules/scylladb.md
  mkdocs.yml
  package-lock.json
  packages/modules/scylladb/jest.config.ts
  packages/modules/scylladb/package.json
  packages/modules/scylladb/src/index.ts
  packages/modules/scylladb/src/scylladb-container.test.ts
  packages/modules/scylladb/src/scylladb-container.ts
  packages/modules/scylladb/tsconfig.build.json
  packages/modules/scylladb/tsconfig.json
Labels: enhancement, minor

#862 Add BigQueryEmulatorContainer to gcloud module
  docs/modules/gcloud.md
  package-lock.json
  packages/modules/gcloud/package.json
  packages/modules/gcloud/src/bigquery-emulator-container.test.ts
  packages/modules/gcloud/src/bigquery-emulator-container.ts
  packages/modules/gcloud/src/cloudstorage-emulator-container.test.ts
  packages/modules/gcloud/src/index.ts
Labels: enhancement, minor

#877 feat(nats): Added support for enabling JetStream in NatsContainer
  docs/modules/nats.md
  packages/modules/nats/src/nats-container.test.ts
  packages/modules/nats/src/nats-container.ts
Labels: enhancement, minor
