Repository testcontainers/testcontainers-node, pull requests merged in 2024-04, with the labels that each got.

#740 Fix Kafka module imports
  packages/modules/kafka/src/kafka-container.ts
  packages/testcontainers/src/index.ts
Labels: bug, patch

#742 Fix error installing dependencies in Node 20x
  package-lock.json
  packages/modules/couchbase/package.json
Labels: bug, patch

#746 Add ChromaDB module
  CONTRIBUTING.md
  README.md
  docs/modules/chromadb.md
  mkdocs.yml
  package-lock.json
  packages/modules/chromadb/jest.config.ts
  packages/modules/chromadb/package.json
  packages/modules/chromadb/src/chromadb-container.test.ts
  packages/modules/chromadb/src/chromadb-container.ts
  packages/modules/chromadb/src/index.ts
  packages/modules/chromadb/tsconfig.build.json
  packages/modules/chromadb/tsconfig.json
Labels: enhancement, minor

#748 Fix parsing registry from env variable to work with trailing slash
  packages/testcontainers/src/container-runtime/image-name.test.ts
  packages/testcontainers/src/container-runtime/image-name.ts
Labels: bug, patch

#751 Fix checking Reaper and the SSHd containers when `_HUB_IMAGE_NAME_PREFIX` provided
  packages/testcontainers/src/container-runtime/image-name.test.ts
  packages/testcontainers/src/container-runtime/image-name.ts
  packages/testcontainers/src/port-forwarder/port-forwarder.ts
  packages/testcontainers/src/reaper/reaper.ts
Labels: bug, patch

#730 Add `OneShotWaitStrategy`
  docs/features/wait-strategies.md
  packages/testcontainers/src/wait-strategies/one-shot-startup-startegy.test.ts
  packages/testcontainers/src/wait-strategies/one-shot-startup-startegy.ts
  packages/testcontainers/src/wait-strategies/startup-check-strategy.test.ts
  packages/testcontainers/src/wait-strategies/startup-check-strategy.ts
  packages/testcontainers/src/wait-strategies/wait.ts
Labels: enhancement, minor

#758 Use new sshd:1.2.0 image
  packages/testcontainers/src/port-forwarder/port-forwarder.ts
Labels: maintenance, minor
