Repository testcontainers/testcontainers-node, pull requests merged in 2024-08, with the labels that each got.

#809 Update the associated link and info of "With files/directories/content"
  docs/features/containers.md
Labels: patch, documentation

#812 Update deps
  package-lock.json
Labels: maintenance, patch

#806 Add support for specifying image platform
  docs/features/containers.md
  packages/testcontainers/src/container-runtime/clients/image/docker-image-client.ts
  packages/testcontainers/src/container-runtime/clients/image/image-client.ts
  packages/testcontainers/src/generic-container/generic-container-builder.ts
  packages/testcontainers/src/generic-container/generic-container.test.ts
  packages/testcontainers/src/generic-container/generic-container.ts
  packages/testcontainers/src/test-container.ts
Labels: enhancement, minor

#814 Replace md5 with sha256 to work on FIPS machines
  packages/testcontainers/src/common/hash.test.ts
  packages/testcontainers/src/common/hash.ts
Labels: enhancement, minor

#821 Update MongoDB docs about `directConnection`
  packages/modules/mongodb/src/mongodb-container.test.ts
Labels: patch, documentation

#805 Add `CloudStorageEmulatorContainer` and `PubSubEmulatorContainer` to gcloud module
  docs/modules/gcloud.md
  package-lock.json
  packages/modules/gcloud/package.json
  packages/modules/gcloud/src/cloudstorage-emulator-container.test.ts
  packages/modules/gcloud/src/cloudstorage-emulator-container.ts
  packages/modules/gcloud/src/index.ts
  packages/modules/gcloud/src/pubsub-emulator-container.test.ts
  packages/modules/gcloud/src/pubsub-emulator-container.ts
Labels: enhancement, minor

#815 Log docker daemon labels
  packages/testcontainers/src/container-runtime/clients/client.ts
  packages/testcontainers/src/container-runtime/clients/types.ts
Labels: enhancement, minor

#822 Update deps 22/08
  package-lock.json
  packages/modules/mongodb/src/mongodb-container.test.ts
Labels: maintenance, patch

#825 Add `autoUpdateExternalUrl` to `CloudStorageEmulatorContainer`
  packages/modules/gcloud/package.json
  packages/modules/gcloud/src/cloudstorage-emulator-container.test.ts
  packages/modules/gcloud/src/cloudstorage-emulator-container.ts
Labels: enhancement, minor
