Repository testcontainers/testcontainers-node, pull requests merged in 2024-02, with the labels that each got.

#693 Add support for `abortOnContainerExit` to HTTP wait strategy
  docs/features/wait-strategies.md
  packages/modules/couchbase/src/couchbase-container.ts
  packages/testcontainers/src/container-runtime/clients/container/docker-container-client.ts
  packages/testcontainers/src/generic-container/abstract-started-container.ts
  packages/testcontainers/src/generic-container/started-generic-container.ts
  packages/testcontainers/src/index.ts
  packages/testcontainers/src/test-container.ts
  packages/testcontainers/src/utils/test-helper.ts
  packages/testcontainers/src/wait-strategies/http-wait-strategy.test.ts
  packages/testcontainers/src/wait-strategies/http-wait-strategy.ts
  packages/testcontainers/src/wait-strategies/wait.ts
Labels: enhancement, minor

#712 Move default container configurations to constructor to allow for overriding
  package-lock.json
  packages/modules/arangodb/src/arangodb-container.ts
  packages/modules/couchbase/src/couchbase-container.ts
  packages/modules/elasticsearch/src/elasticsearch-container.ts
  packages/modules/hivemq/src/hivemq-container.ts
  packages/modules/localstack/src/localstack-container.ts
  packages/modules/mongodb/src/mongodb-container.ts
  packages/modules/mssqlserver/src/mssqlserver-container.ts
  packages/modules/mysql/src/mysql-container.ts
  packages/modules/nats/src/nats-container.ts
  packages/modules/neo4j/src/neo4j-container.ts
  packages/modules/postgresql/src/postgresql-container.ts
  packages/modules/redis/src/redis-container.ts
  packages/modules/selenium/src/selenium-container.ts
  packages/testcontainers/src/generic-container/generic-container.ts
  packages/testcontainers/src/index.ts
Labels: bug, minor

#714 Fix custom image log line
  packages/testcontainers/src/generic-container/generic-container-builder.ts
Labels: maintenance, patch
