Repository testcontainers/testcontainers-node, pull requests merged in 2024-06, with the labels that each got.

#770 Add RabbitMQ module
  docs/modules/rabbitmq.md
  mkdocs.yml
  package-lock.json
  packages/modules/rabbitmq/jest.config.ts
  packages/modules/rabbitmq/package.json
  packages/modules/rabbitmq/src/index.ts
  packages/modules/rabbitmq/src/rabbitmq-container.test.ts
  packages/modules/rabbitmq/src/rabbitmq-container.ts
  packages/modules/rabbitmq/tsconfig.build.json
  packages/modules/rabbitmq/tsconfig.json
Labels: enhancement, minor

#778 Add ollama module
  package-lock.json
  packages/modules/ollama/jest.config.ts
  packages/modules/ollama/package.json
  packages/modules/ollama/src/index.ts
  packages/modules/ollama/src/ollama-container.test.ts
  packages/modules/ollama/src/ollama-container.ts
  packages/modules/ollama/tsconfig.build.json
  packages/modules/ollama/tsconfig.json
  packages/testcontainers/src/container-runtime/clients/client.ts
  packages/testcontainers/src/container-runtime/clients/types.ts
Labels: enhancement, minor

#771 `GenericContainerBuilder` false pull policy should not pull image
  packages/testcontainers/src/generic-container/generic-container-builder.ts
  packages/testcontainers/src/generic-container/generic-container-dockerfile.test.ts
Labels: bug, patch

#780 Update minor deps
  package-lock.json
  package.json
  packages/modules/arangodb/package.json
  packages/modules/couchbase/package.json
  packages/modules/gcloud/package.json
  packages/modules/localstack/package.json
  packages/modules/mongodb/package.json
  packages/modules/mysql/package.json
  packages/modules/nats/package.json
  packages/modules/neo4j/package.json
  packages/modules/postgresql/package.json
  packages/modules/qdrant/package.json
  packages/modules/rabbitmq/package.json
  packages/modules/redis/package.json
  packages/modules/selenium/package.json
  packages/modules/weaviate/package.json
  packages/testcontainers/package.json
Labels: maintenance, patch

#787 Add logs around resolving a container runtime
  .github/workflows/test.yml
  packages/testcontainers/src/container-runtime/clients/client.ts
Labels: enhancement, patch

#784 Added Ollama module docs
  docs/modules/ollama.md
  mkdocs.yml
  packages/modules/ollama/src/ollama-container.test.ts
Labels: maintenance, patch
