Repository testcontainers/testcontainers-node, pull requests merged in 2024-07, with the labels that each got.

#788 Fix OllamaContainer's commitToImage
  packages/modules/ollama/src/ollama-container.test.ts
  packages/modules/ollama/src/ollama-container.ts
Labels: bug, patch

#790 Include Redpanda assets in build artifact
  packages/modules/redpanda/package.json
  packages/modules/redpanda/src/assets/bootstrap.yaml
  packages/modules/redpanda/src/assets/redpanda.yaml.hbs
  packages/modules/redpanda/src/redpanda-container.ts
Labels: bug, patch

#794 Log stacktrace when container runtime strategy throws
  packages/testcontainers/src/container-runtime/clients/client.ts
Labels: maintenance, patch

#795 Docker runtimes may be undefined
  packages/modules/ollama/src/ollama-container.ts
  packages/testcontainers/src/container-runtime/clients/client.ts
Labels: bug, patch

#764 Fix fetching registry credentials when using Gcloud cred helper
  packages/testcontainers/src/container-runtime/auth/credential-provider.test.ts
  packages/testcontainers/src/container-runtime/auth/credential-provider.ts
Labels: bug, patch

#796 Update minor deps
  package-lock.json
  package.json
  packages/modules/couchbase/package.json
  packages/modules/elasticsearch/package.json
  packages/modules/gcloud/package.json
  packages/modules/localstack/package.json
  packages/modules/mongodb/package.json
  packages/modules/mssqlserver/package.json
  packages/modules/mysql/package.json
  packages/modules/nats/package.json
  packages/modules/neo4j/package.json
  packages/modules/qdrant/package.json
  packages/modules/redis/package.json
  packages/modules/selenium/package.json
Labels: maintenance, patch

#801 MSSQL Docker image, 2022-latest -> 2022-CU13-ubuntu-22.04
  packages/modules/mssqlserver/src/mssqlserver-container.ts
Labels: maintenance, minor

#782 Add `DatastoreEmulatorContainer` to gcloud module
  docs/modules/gcloud.md
  package-lock.json
  packages/modules/gcloud/package.json
  packages/modules/gcloud/src/datastore-emulator-container.test.ts
  packages/modules/gcloud/src/datastore-emulator-container.ts
  packages/modules/gcloud/src/index.ts
Labels: enhancement, minor

#800 Support custom compose project names
  docs/features/compose.md
  packages/testcontainers/src/docker-compose-environment/docker-compose-environment.test.ts
  packages/testcontainers/src/docker-compose-environment/docker-compose-environment.ts
Labels: enhancement, minor

#789 Make `HealthCheckWaitStrategy` event based
  packages/testcontainers/fixtures/docker-compose/docker-compose-with-healthcheck-unhealthy.yml
  packages/testcontainers/src/container-runtime/clients/container/container-client.ts
  packages/testcontainers/src/container-runtime/clients/container/docker-container-client.ts
  packages/testcontainers/src/docker-compose-environment/docker-compose-environment.test.ts
  packages/testcontainers/src/wait-strategies/health-check-wait-strategy.ts
Labels: enhancement, minor

#777 Replace `node-fetch` with Node.js' native `fetch`
  package-lock.json
  packages/modules/couchbase/src/couchbase-container.test.ts
  packages/modules/couchbase/src/couchbase-container.ts
  packages/modules/ollama/src/ollama-container.test.ts
  packages/modules/redpanda/package.json
  packages/testcontainers/package.json
  packages/testcontainers/src/docker-compose-environment/docker-compose-environment.test.ts
  packages/testcontainers/src/generic-container/generic-container.test.ts
  packages/testcontainers/src/utils/test-helper.ts
  packages/testcontainers/src/wait-strategies/http-wait-strategy.ts
  tsconfig.base.json
Labels: maintenance, minor

#791 Bump archiver from 5.3.2 to 7.0.1
  package-lock.json
  packages/testcontainers/package.json
Labels: maintenance, minor
