Repository testcontainers/testcontainers-node, pull requests merged in 2025-01, with the labels that each got.

#890 Optimise file-lock retry options
  packages/testcontainers/src/common/file-lock.ts
Labels: enhancement, minor

#888 NPM audit
  package-lock.json
Labels: maintenance, patch

#882 MySQL add `isRoot` parameter to `executeQuery`
  packages/modules/mysql/src/mysql-container.test.ts
  packages/modules/mysql/src/mysql-container.ts
Labels: enhancement, minor

#892 Add Mockserver module
  docs/modules/mockserver.md
  mkdocs.yml
  package-lock.json
  packages/modules/mockserver/jest.config.ts
  packages/modules/mockserver/package.json
  packages/modules/mockserver/src/index.ts
  packages/modules/mockserver/src/mockserver-container.test.ts
  packages/modules/mockserver/src/mockserver-container.ts
  packages/modules/mockserver/tsconfig.build.json
  packages/modules/mockserver/tsconfig.json
Labels: enhancement, minor

#893 Add MinIO module
  docs/modules/minio.md
  mkdocs.yml
  package-lock.json
  packages/modules/minio/jest.config.ts
  packages/modules/minio/package.json
  packages/modules/minio/src/dummy-file.txt
  packages/modules/minio/src/index.ts
  packages/modules/minio/src/minio-container.test.ts
  packages/modules/minio/src/minio-container.ts
  packages/modules/minio/tsconfig.build.json
  packages/modules/minio/tsconfig.json
Labels: enhancement, minor

#891 Add Toxiproxy module
  docs/modules/toxiproxy.md
  mkdocs.yml
  package-lock.json
  packages/modules/toxiproxy/jest.config.ts
  packages/modules/toxiproxy/package.json
  packages/modules/toxiproxy/src/index.ts
  packages/modules/toxiproxy/src/toxiproxy-container.test.ts
  packages/modules/toxiproxy/src/toxiproxy-container.ts
  packages/modules/toxiproxy/tsconfig.build.json
  packages/modules/toxiproxy/tsconfig.json
Labels: enhancement, minor

#894 Add EventStoreDB module
  docs/modules/eventstoredb.md
  mkdocs.yml
  package-lock.json
  packages/modules/eventstoredb/jest.config.ts
  packages/modules/eventstoredb/package.json
  packages/modules/eventstoredb/src/eventstoredb-container.test.ts
  packages/modules/eventstoredb/src/eventstoredb-container.ts
  packages/modules/eventstoredb/src/index.ts
  packages/modules/eventstoredb/tsconfig.build.json
  packages/modules/eventstoredb/tsconfig.json
Labels: enhancement, minor

#895 Support restart on 5 containers with previously fixed ports
  packages/modules/cassandra/src/cassandra-container.test.ts
  packages/modules/cassandra/src/cassandra-container.ts
  packages/modules/elasticsearch/src/elasticsearch-container.test.ts
  packages/modules/elasticsearch/src/elasticsearch-container.ts
  packages/modules/mariadb/src/mariadb-container.test.ts
  packages/modules/mariadb/src/mariadb-container.ts
  packages/modules/mysql/src/mysql-container.test.ts
  packages/modules/mysql/src/mysql-container.ts
  packages/modules/scylladb/src/scylladb-container.test.ts
  packages/modules/scylladb/src/scylladb-container.ts
Labels: bug, patch

#902 Add support for Docker credential providers which do not implement list command
  packages/testcontainers/src/container-runtime/auth/credential-provider.test.ts
  packages/testcontainers/src/container-runtime/auth/credential-provider.ts
Labels: bug, patch
