Repository testcontainers/testcontainers-node, pull requests merged in 2025-04, with the labels that each got.

#968 Log stream fix for Podman
  packages/modules/kafka/src/kafka-container.test.ts
  packages/modules/localstack/src/localstack-container.test.ts
  packages/testcontainers/src/container-runtime/clients/container/docker-container-client.ts
Labels: bug, patch

#970 Update vitest + npm audit
  package-lock.json
  package.json
Labels: dependencies, patch

#964 Add SocatContainer
  docs/features/containers.md
  packages/testcontainers/src/index.ts
  packages/testcontainers/src/socat/socat-container.test.ts
  packages/testcontainers/src/socat/socat-container.ts
Labels: enhancement, minor

#972 Fix healthcheck for Postgis
  docs/modules/postgresql.md
  package-lock.json
  package.json
  packages/modules/postgresql/src/pgvector-container.test.ts
  packages/modules/postgresql/src/postgis-container.test.ts
  packages/modules/postgresql/src/postgresql-container-snapshot.test.ts
  packages/modules/postgresql/src/postgresql-container.test.ts
  packages/modules/postgresql/src/postgresql-container.ts
  packages/modules/postgresql/src/timescale-container.test.ts
  packages/testcontainers/src/generic-container/generic-container.ts
  packages/testcontainers/src/generic-container/started-generic-container.ts
  packages/testcontainers/src/test-container.ts
  vitest.config.ts
Labels: bug, patch

#976 Update wait-strategies.md
  docs/features/wait-strategies.md
Labels: documentation

#977 Simplify log-wait-strategy
  packages/testcontainers/src/wait-strategies/log-wait-strategy.test.ts
  packages/testcontainers/src/wait-strategies/log-wait-strategy.ts
Labels: maintenance, patch

#980 Bump `dockerode` dependency to `4.0.5`
  package-lock.json
  packages/testcontainers/package.json
Labels: dependencies, patch

#984 Revert "Simplify log-wait-strategy (#977)"
  packages/testcontainers/src/wait-strategies/log-wait-strategy.test.ts
  packages/testcontainers/src/wait-strategies/log-wait-strategy.ts
Labels: bug, patch
