Repository testcontainers/testcontainers-node, pull requests merged in 2025-08, with the labels that each got.

#1068 Implement support for specifying the protocol when exposing ports
  docs/features/containers.md
  packages/modules/azurite/src/azurite-container.ts
  packages/testcontainers/src/generic-container/abstract-started-container.ts
  packages/testcontainers/src/generic-container/generic-container.test.ts
  packages/testcontainers/src/generic-container/generic-container.ts
  packages/testcontainers/src/generic-container/inspect-container-util-ports-exposed.test.ts
  packages/testcontainers/src/generic-container/started-generic-container.ts
  packages/testcontainers/src/test-container.ts
  packages/testcontainers/src/types.ts
  packages/testcontainers/src/utils/bound-ports.test.ts
  packages/testcontainers/src/utils/bound-ports.ts
  packages/testcontainers/src/utils/map-inspect-result.ts
  packages/testcontainers/src/utils/port.test.ts
  packages/testcontainers/src/utils/port.ts
  packages/testcontainers/src/utils/test-helper.ts
  packages/testcontainers/src/wait-strategies/host-port-wait-strategy.test.ts
  packages/testcontainers/src/wait-strategies/host-port-wait-strategy.ts
  packages/testcontainers/src/wait-strategies/utils/port-check.test.ts
  packages/testcontainers/src/wait-strategies/utils/port-check.ts
Labels: enhancement, minor

#1088 Fix resource quota being rejected when contains decimals
  packages/testcontainers/src/generic-container/generic-container-resources-quota.test.ts
  packages/testcontainers/src/generic-container/generic-container.ts
Labels: bug, patch

#1100 Move more test images to Dockerfiles for Dependabot
  packages/modules/chromadb/Dockerfile
  packages/modules/chromadb/src/chromadb-container.test.ts
  packages/modules/k3s/Dockerfile
  packages/modules/k3s/src/k3s-container.test.ts
  packages/modules/localstack/Dockerfile
  packages/modules/localstack/src/localstack-container.test.ts
  packages/modules/neo4j/src/neo4j-container.test.ts
  packages/modules/redis/Dockerfile
  packages/modules/redis/src/redis-container.test.ts
Labels: maintenance

#1105 Fix redpanda missing `redpanda.yaml.hbs`
  packages/modules/redpanda/package.json
Labels: bug, patch

#1114 Remove msw override
  package-lock.json
  package.json
  packages/modules/gcloud/package.json
Labels: dependencies, javascript

#1117 Add username option to Valkey container
  docs/modules/valkey.md
  package-lock.json
  packages/modules/valkey/src/valkey-container.test.ts
  packages/modules/valkey/src/valkey-container.ts
Labels: enhancement, minor
