Repository testcontainers/testcontainers-node, pull requests merged in 2025-03, with the labels that each got.

#914 Fix PostgreSQL container restart
  packages/modules/postgresql/src/postgresql-container.test.ts
  packages/modules/postgresql/src/postgresql-container.ts
  packages/testcontainers/src/container-runtime/clients/container/docker-container-client.ts
  packages/testcontainers/src/generic-container/generic-container.ts
Labels: bug, patch

#910 Add CockroachDB module
  docs/modules/cockroachdb.md
  mkdocs.yml
  package-lock.json
  packages/modules/cockroachdb/jest.config.ts
  packages/modules/cockroachdb/package.json
  packages/modules/cockroachdb/src/cockroachdb-container.test.ts
  packages/modules/cockroachdb/src/cockroachdb-container.ts
  packages/modules/cockroachdb/src/index.ts
  packages/modules/cockroachdb/tsconfig.build.json
  packages/modules/cockroachdb/tsconfig.json
Labels: enhancement, minor

#917 Update docs to demonstrate specifying Qdrant version
  packages/modules/qdrant/src/qdrant-container.test.ts
  packages/modules/qdrant/src/qdrant-container.ts
Labels: maintenance, patch

#920 GHA workflow job names
  .github/workflows/test.yml
Labels: maintenance

#922 Fix lambda container is dropped by ryuk (#848)
  packages/modules/localstack/src/localstack-container.test.ts
  packages/modules/localstack/src/localstack-container.ts
Labels: bug, patch

#929 Fix flaky Selenium test
  packages/modules/selenium/src/selenium-container.test.ts
  packages/testcontainers/src/container-runtime/utils/image-exists.test.ts
Labels: maintenance

#930 Fix flaky healthcheck timeout test
  packages/testcontainers/fixtures/docker-compose/docker-compose-with-healthcheck-with-start-period.yml
  packages/testcontainers/src/docker-compose-environment/docker-compose-environment.test.ts
  packages/testcontainers/src/wait-strategies/health-check-wait-strategy.test.ts
Labels: maintenance

#931 Upgrade linting libraries
  .eslintignore
  .eslintrc.js
  .prettierrc
  eslint.config.js
  package-lock.json
  package.json
  packages/modules/arangodb/src/arangodb-container.ts
  packages/modules/couchbase/src/couchbase-service.ts
  packages/modules/gcloud/src/bigquery-emulator-container.ts
  packages/modules/gcloud/src/cloudstorage-emulator-container.test.ts
  packages/modules/gcloud/src/cloudstorage-emulator-container.ts
  packages/modules/gcloud/src/pubsub-emulator-container.ts
  packages/modules/k3s/src/k3s-container.ts
  packages/modules/neo4j/src/neo4j-container.ts
  packages/modules/redis/src/redis-container.ts
  packages/modules/toxiproxy/src/toxiproxy-container.ts
  packages/modules/valkey/src/valkey-container.ts
  packages/testcontainers/src/common/logger.ts
  packages/testcontainers/src/container-runtime/auth/credential-provider.test.ts
  packages/testcontainers/src/container-runtime/clients/compose/compose-client.ts
  packages/testcontainers/src/container-runtime/clients/image/docker-image-client.ts
  packages/testcontainers/src/generic-container/generic-container-lifecycle.test.ts
  packages/testcontainers/src/reaper/reaper.ts
  packages/testcontainers/src/wait-strategies/log-wait-strategy.ts
  packages/testcontainers/src/wait-strategies/utils/port-check.ts
Labels: maintenance

#935 Do not replace user-provided Localstack `LAMBDA_DOCKER_FLAGS`
  packages/modules/localstack/src/localstack-container.test.ts
  packages/modules/localstack/src/localstack-container.ts
Labels: bug, patch

#932 Add ability to copy archives into containers
  docs/features/containers.md
  packages/testcontainers/src/generic-container/abstract-started-container.ts
  packages/testcontainers/src/generic-container/generic-container.ts
  packages/testcontainers/src/generic-container/started-generic-container.ts
  packages/testcontainers/src/test-container.ts
  packages/testcontainers/src/types.ts
Labels: enhancement, minor

#934 Add cosmos db emulator module
  docs/modules/cosmosdb.md
  mkdocs.yml
  package-lock.json
  packages/modules/azurecosmosdb/package.json
  packages/modules/azurecosmosdb/src/azure-cosmosdb-emulator-container.test.ts
  packages/modules/azurecosmosdb/src/azure-cosmosdb-emulator-container.ts
  packages/modules/azurecosmosdb/src/index.ts
  packages/modules/azurecosmosdb/tsconfig.build.json
  packages/modules/azurecosmosdb/tsconfig.json
  packages/testcontainers/src/index.ts
Labels: enhancement, minor

#939 Implement `withAutoRemove` #905
  docs/features/containers.md
  packages/testcontainers/src/docker-compose-environment/docker-compose-environment.ts
  packages/testcontainers/src/generic-container/generic-container.test.ts
  packages/testcontainers/src/generic-container/generic-container.ts
  packages/testcontainers/src/generic-container/started-generic-container.ts
  packages/testcontainers/src/test-container.ts
  packages/testcontainers/src/utils/test-helper.ts
Labels: enhancement, minor

#940 Update ChromaDB + improve docs and tests
  docs/modules/chromadb.md
  package-lock.json
  packages/modules/chromadb/package.json
  packages/modules/chromadb/src/chromadb-container.test.ts
  packages/modules/chromadb/src/chromadb-container.ts
Labels: enhancement, minor

#941 Add `TESTCONTAINERS_RYUK_VERBOSE` setting
  docs/configuration.md
  packages/testcontainers/src/reaper/reaper.test.ts
  packages/testcontainers/src/reaper/reaper.ts
  packages/testcontainers/src/utils/labels.ts
Labels: enhancement, minor

#937 Minor fixes
  package-lock.json
  package.json
  packages/modules/arangodb/package.json
  packages/modules/azurecosmosdb/package.json
  packages/modules/azurite/package.json
  packages/modules/cassandra/package.json
  packages/modules/cassandra/src/cassandra-container.ts
  packages/modules/chromadb/package.json
  packages/modules/cockroachdb/package.json
  packages/modules/couchbase/package.json
  packages/modules/elasticsearch/package.json
  packages/modules/eventstoredb/package.json
  packages/modules/gcloud/package.json
  packages/modules/hivemq/package.json
  packages/modules/k3s/package.json
  packages/modules/kafka/package.json
  packages/modules/localstack/package.json
  packages/modules/mariadb/package.json
  packages/modules/minio/package.json
  packages/modules/mongodb/package.json
  packages/modules/mssqlserver/package.json
  packages/modules/mysql/package.json
  packages/modules/nats/package.json
  packages/modules/neo4j/package.json
  packages/modules/ollama/package.json
  packages/modules/postgresql/package.json
  packages/modules/qdrant/package.json
  packages/modules/qdrant/src/qdrant-container.test.ts
  packages/modules/rabbitmq/package.json
  packages/modules/rabbitmq/src/rabbitmq-container.test.ts
  packages/modules/redis/package.json
  packages/modules/redpanda/package.json
  packages/modules/scylladb/package.json
  packages/modules/selenium/package.json
  packages/modules/toxiproxy/package.json
  packages/modules/valkey/package.json
  packages/modules/weaviate/package.json
  packages/testcontainers/package.json
  packages/testcontainers/src/utils/port-generator.ts
  vitest.config.ts
Labels: maintenance

#942 Couchbase: add missing exports and fix sonar suggestions
  .github/scripts/changed-modules.sh
  packages/modules/couchbase/src/bucket-definition.ts
  packages/modules/couchbase/src/couchbase-container.ts
  packages/modules/couchbase/src/couchbase-service.ts
  packages/modules/couchbase/src/index.ts
Labels: bug, patch

#945 Vitest stub env refactor
  packages/testcontainers/src/container-runtime/auth/get-auth-config.test.ts
  packages/testcontainers/src/container-runtime/image-name.test.ts
  packages/testcontainers/src/generic-container/generic-container-reuse.test.ts
  packages/testcontainers/src/reaper/reaper.test.ts
  vitest.config.ts
Labels: maintenance

#949 Fix scrollbar in docs #948
  mkdocs.yml
Labels: maintenance

#951 Fix flaky port forwarder tests
  packages/testcontainers/src/port-forwarder/port-forwarder-reuse.test.ts
  packages/testcontainers/src/port-forwarder/port-forwarder.test.ts
  packages/testcontainers/src/utils/port-generator.ts
  packages/testcontainers/src/utils/test-helper.ts
Labels: maintenance

#947 Add missing reaper tests
  docs/supported-container-runtimes.md
  packages/testcontainers/src/port-forwarder/port-forwarder.ts
  packages/testcontainers/src/reaper/reaper.test.ts
  packages/testcontainers/src/reaper/reaper.ts
Labels: maintenance

#950 Update docs
  docs/features/containers.md
  docs/features/images.md
  docs/index.md
  docs/site/language-logos/clojure.svg
  docs/site/language-logos/elixir.svg
  docs/site/language-logos/php.svg
  docs/site/language-logos/scala.svg
  packages/testcontainers/src/generic-container/generic-container-reuse.test.ts
Labels: maintenance

#956 Tidy up imports
  packages/modules/azurecosmosdb/src/azure-cosmosdb-emulator-container.test.ts
  packages/modules/couchbase/src/couchbase-container.test.ts
  packages/modules/gcloud/src/firestore-emulator-container.test.ts
  packages/modules/kafka/src/kafka-container.test.ts
  packages/modules/minio/src/minio-container.test.ts
  packages/modules/redis/src/redis-container.test.ts
  packages/modules/valkey/src/valkey-container.test.ts
Labels: maintenance

#955 Add buildkit support
  docs/features/images.md
  package-lock.json
  packages/testcontainers/fixtures/docker-compose/docker-compose-with-buildkit/Dockerfile
  packages/testcontainers/fixtures/docker-compose/docker-compose-with-buildkit/docker-compose.yml
  packages/testcontainers/fixtures/docker-compose/docker-compose-with-buildkit/index.js
  packages/testcontainers/fixtures/docker/docker-with-buildkit/Dockerfile
  packages/testcontainers/fixtures/docker/docker-with-buildkit/index.js
  packages/testcontainers/package.json
  packages/testcontainers/src/docker-compose-environment/docker-compose-environment.test.ts
  packages/testcontainers/src/generic-container/generic-container-builder.ts
  packages/testcontainers/src/generic-container/generic-container-dockerfile.test.ts
Labels: enhancement, minor

#954 Improve PortCheck logging for distroless images
  packages/testcontainers/fixtures/docker/docker-no-shell/Dockerfile
  packages/testcontainers/fixtures/docker/docker-no-shell/index.js
  packages/testcontainers/src/wait-strategies/utils/port-check.test.ts
  packages/testcontainers/src/wait-strategies/utils/port-check.ts
Labels: enhancement, minor

#959 Remove Docker no shell fixture
  packages/testcontainers/fixtures/docker/docker-no-shell/Dockerfile
  packages/testcontainers/fixtures/docker/docker-no-shell/index.js
Labels: maintenance

#958 Docs: clarified timeout unit in different places
  docs/features/compose.md
  docs/features/containers.md
  docs/features/wait-strategies.md
Labels: maintenance

#957 Update quickstart docs
  docs/quickstart.md
  docs/quickstart/global-setup.md
  docs/quickstart/install.md
  docs/quickstart/logging.md
  docs/quickstart/usage.md
  mkdocs.yml
Labels: maintenance

#961 Add snapshot support to postgres module
  docs/modules/postgresql.md
  packages/modules/postgresql/src/postgresql-container.test.ts
  packages/modules/postgresql/src/postgresql-container.ts
Labels: enhancement, minor
