Repository testcontainers/testcontainers-node, pull requests merged in 2025-07, with the labels that each got.

#1051 Change KurrentDB protocol from `esdb` to `kurrentdb`
  packages/modules/kurrentdb/src/kurrentdb-container.ts
Labels: enhancement, minor

#1053 Add support for Confluent Kafka 8
  docs/modules/kafka.md
  package-lock.json
  packages/modules/kafka/Dockerfile
  packages/modules/kafka/package.json
  packages/modules/kafka/src/kafka-container-7.test.ts
  packages/modules/kafka/src/kafka-container-latest.test.ts
  packages/modules/kafka/src/kafka-container.ts
  packages/modules/kafka/src/test-helper.ts
  packages/modules/kafka/tsconfig.build.json
Labels: enhancement, minor

#1059 Add `getSecureUrl` in mockserver's module
  docs/modules/mockserver.md
  packages/modules/mockserver/src/mockserver-container.test.ts
  packages/modules/mockserver/src/mockserver-container.ts
Labels: enhancement, minor

#1073 Wildcard for dependabot Dockerfile directories
  .github/dependabot.yml
Labels: maintenance

#1067 Run tests concurrently
  docs/modules/cassandra.md
  packages/modules/cassandra/src/cassandra-container.test.ts
  packages/modules/gcloud/src/cloudstorage-emulator-container.test.ts
  packages/modules/gcloud/src/firestore-emulator-container.test.ts
  packages/modules/kurrentdb/src/kurrentdb-container.test.ts
  packages/testcontainers/src/common/index.ts
  packages/testcontainers/src/container-runtime/auth/cred-helpers.ts
  packages/testcontainers/src/container-runtime/auth/credential-provider.test.ts
  packages/testcontainers/src/container-runtime/auth/get-auth-config.test.ts
  packages/testcontainers/src/container-runtime/image-name.test.ts
  packages/testcontainers/src/container-runtime/strategies/configuration-strategy.test.ts
  packages/testcontainers/src/container-runtime/strategies/rootless-unix-socket-strategy.test.ts
  packages/testcontainers/src/container-runtime/strategies/testcontainers-host-strategy.test.ts
  packages/testcontainers/src/container-runtime/strategies/unix-socket-strategy.test.ts
  packages/testcontainers/src/container-runtime/strategies/utils/config.test.ts
  packages/testcontainers/src/container-runtime/utils/image-exists.test.ts
  packages/testcontainers/src/container-runtime/utils/lookup-host-ips.test.ts
  packages/testcontainers/src/container-runtime/utils/resolve-host.test.ts
  packages/testcontainers/src/generic-container/generic-container-lifecycle.test.ts
  packages/testcontainers/src/index.ts
  packages/testcontainers/src/port-forwarder/port-forwarder-reuse.test.ts
  packages/testcontainers/src/port-forwarder/port-forwarder.test.ts
  packages/testcontainers/src/reaper/reaper.test.ts
  packages/testcontainers/src/wait-strategies/utils/port-check.test.ts
  vitest.config.ts
Labels: maintenance

#1076 Add Spanner module
  docs/modules/gcloud.md
  package-lock.json
  packages/modules/gcloud/Dockerfile
  packages/modules/gcloud/package.json
  packages/modules/gcloud/src/bigquery-emulator-container.ts
  packages/modules/gcloud/src/index.ts
  packages/modules/gcloud/src/spanner-emulator-container.test.ts
  packages/modules/gcloud/src/spanner-emulator-container.ts
  packages/modules/gcloud/src/spanner-emulator-helper.test.ts
  packages/modules/gcloud/src/spanner-emulator-helper.ts
Labels: enhancement, minor

#1084 Fix for Gcloud module eagerly importing @google-cloud/spanner
  packages/modules/gcloud/src/spanner-emulator-helper.test.ts
  packages/modules/gcloud/src/spanner-emulator-helper.ts
Labels: bug, patch
