Repository testcontainers/testcontainers-node, pull requests merged in 2025-05, with the labels that each got.

#998 Add `Wait.forListeningPorts` to Cassandra/Cockroach/Postgres modules
  packages/modules/cassandra/src/cassandra-container.ts
  packages/modules/cockroachdb/src/cockroachdb-container.ts
  packages/modules/postgresql/src/postgresql-container.ts
Labels: enhancement, minor

#994 Support Neo4j plugins other than Apoc
  docs/modules/neo4j.md
  packages/modules/neo4j/src/index.ts
  packages/modules/neo4j/src/neo4j-container.test.ts
  packages/modules/neo4j/src/neo4j-container.ts
Labels: enhancement, minor

#1005 Add support for redis-stack containers
  docs/modules/redis.md
  packages/modules/redis/src/redis-container.test.ts
  packages/modules/redis/src/redis-container.ts
Labels: enhancement, minor

#1007 Export container classes from the Etcd module
  packages/modules/etcd/src/index.ts
Labels: bug, patch

#1010 Pin gcloud cloud-sdk image version
  packages/modules/gcloud/src/datastore-emulator-container.ts
  packages/modules/gcloud/src/firestore-emulator-container.ts
Labels: maintenance

#1009 Upgrade NATS library used for tests
  package-lock.json
  packages/modules/nats/package.json
  packages/modules/nats/src/nats-container.test.ts
Labels: maintenance, patch

#1011 NATS: Add codec, scratch compatibility
  packages/modules/nats/src/nats-container.test.ts
  packages/modules/nats/src/nats-container.ts
Labels: enhancement, minor

#962 Container stop timeouts should be in milliseconds
  docs/features/compose.md
  docs/features/containers.md
  docs/features/wait-strategies.md
  packages/modules/couchbase/src/couchbase-container.ts
  packages/testcontainers/src/common/index.ts
  packages/testcontainers/src/common/retry.ts
  packages/testcontainers/src/common/time.test.ts
  packages/testcontainers/src/common/time.ts
  packages/testcontainers/src/container-runtime/clients/compose/compose-client.ts
  packages/testcontainers/src/container-runtime/clients/container/docker-container-client.ts
  packages/testcontainers/src/docker-compose-environment/docker-compose-environment.ts
  packages/testcontainers/src/generic-container/generic-container.ts
  packages/testcontainers/src/wait-strategies/composite-wait-strategy.ts
  packages/testcontainers/src/wait-strategies/health-check-wait-strategy.ts
  packages/testcontainers/src/wait-strategies/host-port-wait-strategy.ts
  packages/testcontainers/src/wait-strategies/http-wait-strategy.ts
  packages/testcontainers/src/wait-strategies/log-wait-strategy.ts
  packages/testcontainers/src/wait-strategies/shell-wait-strategy.ts
  packages/testcontainers/src/wait-strategies/startup-check-strategy.ts
  packages/testcontainers/src/wait-strategies/wait-strategy.ts
Labels: enhancement, major

#901 Rename EventStoreDB to KurrentDB
  docs/modules/eventstoredb.md
  docs/modules/kurrentdb.md
  mkdocs.yml
  package-lock.json
  packages/modules/eventstoredb/src/eventstoredb-container.ts
  packages/modules/eventstoredb/src/index.ts
  packages/modules/kurrentdb/package.json
  packages/modules/kurrentdb/src/index.ts
  packages/modules/kurrentdb/src/kurrentdb-container.test.ts
  packages/modules/kurrentdb/src/kurrentdb-container.ts
  packages/modules/kurrentdb/tsconfig.build.json
  packages/modules/kurrentdb/tsconfig.json
Labels: maintenance, major

#1013 Add dependabot
  .github/dependabot.yml
Labels: maintenance

#1016 Refactor workflows
  .github/actions/colima-setup/action.yml
  .github/actions/docker-rootless-setup/action.yml
  .github/actions/npm-setup/action.yml
  .github/actions/podman-setup/action.yml
  .github/actions/rancher-desktop-setup/action.yml
  .github/release-drafter.yml
  .github/workflows/checks.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/test-template.yml
  .github/workflows/windows-test.yml
  README.md
  package.json
Labels: maintenance
